language: python
python:
    - "3.6"
before_install:
    before_install:
    - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - py.test
after_success:
    - coveralls
