language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - python setup.py install
script:
    - python test_DeriveAlive.py
after_success:
    - coveralls
